### ISSUE TITLE
Support "sensitive" in OutputSpec

### ISSUE THREAD

**Issue by mcfearsome** [hashicorp/terraform-k8s#39] opened 2020-04-28 18:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add the ability to mark an output as sensitive to prevent output in logs

### Potential Terraform Configuration

```yaml
  outputs:
  - key: aws_access_key_id
    moduleOutputName: aws_access_key_id
  - key: aws_secret_access_key
    moduleOutputName: aws_secret_access_key
    sensitive: true
```

**Comment by dak1n1** [comment] 2020-06-03 23:14
I think the behavior you're looking for is already supported. I'll walk you through one possible scenario, although it could be different from yours:

The outputs are defined by the module, and the module is specified by the user when they create the CR. For example, here we're creating a Workspace CR and specifying a module named "terraform-aws-modules/sqs/aws":

```
# workspace.yml
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
[...]
module:
   source: "terraform-aws-modules/sqs/aws"
   version: "2.0.0"
```

If you happen to be using a module that you own (IE, a custom module in your git repo), then you could have some control over outputs on this level. But if that's not the case, there are still some options.

In this example, we would have the option of using outputs named [this_sqs_queue_id, this_sqs_queue_arn, this_sqs_queue_name](https://github.com/terraform-aws-modules/terraform-aws-sqs/blob/master/outputs.tf) because those are written into the module.

We can then choose from the available output options and specify exactly which ones we want visible in the Workspace status and logs. In this example, we've chosen only to show the `this_sqs_queue_id`, and omit the others:

```
outputs:
   - key: url
     moduleOutputName: this_sqs_queue_id
```

So to prevent any sensitive data from showing up in the Workspace CR status, I think it would work to simply omit the names of the sensitive outputs. (The example was taken from here, if you want to see the full workspace.yml: https://www.hashicorp.com/blog/creating-workspaces-with-the-hashicorp-terraform-operator-for-kubernetes/ )

When I ran it, only the specified output appeared in the apply log:

```
Terraform v0.12.25
Initializing plugins and modules...
2020/06/03 23:00:38 [DEBUG] Using modified User-Agent: Terraform/0.12.25 TFC/901765b936
module.operator.aws_sqs_queue.this[0]: Creating...
module.operator.aws_sqs_queue.this[0]: Creation complete after 2s [id=https://sqs.us-west-2.amazonaws.com/853745824908/greetings.fifo]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

url = https://sqs.us-west-2.amazonaws.com/853745824908/greetings.fifo
```

And my workspace status only contained the output that I specified:

```
$ kubectl describe workspace greetings -n preprod
[...]
Status:
  Outputs:
    Key:         url
    Value:       "https://sqs.us-west-2.amazonaws.com/853745824908/greetings.fifo"
[...]
```

If this is doesn't solve the problem, we would just need some more information to reproduce the scenario you have in mind (like an example CR).

**Comment by mcfearsome** [comment] 2020-06-03 23:46
Yes, but I need the sensitive outputs, just don’t want these values in the cloud logs.  I can put together a PR eventually, just busy atm.

**Comment by rojopolis** [comment] 2020-06-04 00:16
Would it make sense to route sensitive outputs to a k8s secret rather than the configmap?

**Comment by dak1n1** [comment] 2020-06-11 21:53
I brought this issue up in a meeting recently and it was received positively by the team. It seems like a valuable feature, and it's in our work queue. (But a lot of other things are in the queue too).

**Comment by koikonom** [comment] 2021-02-03 07:56
Hi @mcfearsome, can you please take a look at #80 and let us know if it covers your use case?

**Comment by aareet** [comment] 2021-03-09 23:06
Closing since I believe this is covered by #80 and has been waiting response for about a month. @mcfearsome please feel free to reopen if that's not the case :)

**Closed by aareet** 2021-03-09 23:06 UTC
Labels: enhancement
