### ISSUE TITLE
Outputs cannot be marked as sensitive

### ISSUE THREAD

**Issue by EmmanuelOgiji** [hashicorp/terraform-k8s#123] opened 2022-02-09 18:10 UTC
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### terraform-k8s & Kubernetes Version

Image: hashicorp/terraform-k8s:1.1.0
### Affected Resource(s)

Sensitive Outputs

### Terraform Configuration Files

There seems to be no way to set outputs to have sensitive = true in the yaml and then propagate to the config map terraform configuration

i.e.

The following yaml snippet:
outputs:
    - key: DB_HOST
      moduleOutputName: primary_host
    - key: DB_NAME
      moduleOutputName: db_name
    - key: DB_USER
      moduleOutputName: db_user
    - key: DB_PASSWORD
      moduleOutputName: db_password
      sensitive: true

yields the following hcl terraform:
output "DB_HOST" {
    value = module.operator.primary_host
  }
  output "DB_NAME" {
    value = module.operator.db_name
  }
  output "DB_USER" {
    value = module.operator.db_user
  }
  output "DB_PASSWORD" {
    value = module.operator.db_password
  }

Thus the sensitive output cannot be retrieved

### Expected Behavior

The HCL should be rendered as 
output "DB_PASSWORD" {
    value = module.operator.db_password
    sensitive = true
  }

Thereafter, the output can be read

**Comment by redeux** [comment] 2022-02-11 12:09
Hi @EmmanuelOgiji. This seems to be a duplicate of #107. I'm going to close this for consolidation. If you disagree that this is a duplicate please feel free to reopen it and provide additional context.

**Closed by redeux** 2022-02-11 12:09 UTC
Labels: bug
